package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

/**
 * Alarma generated by hbm2java
 */
public class Alarma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7192019348422642651L;
	
	private long idAlarma;
	private String descripcion;
	private String tiempoEjecucion;
	private String estatus;

	public Alarma() {
	}

	public Alarma(long idAlarma, String descripcion, String tiempoEjecucion, String estatus) {
		this.idAlarma = idAlarma;
		this.descripcion = descripcion;
		this.tiempoEjecucion = tiempoEjecucion;
		this.estatus = estatus;
	}

	public long getIdAlarma() {
		return this.idAlarma;
	}

	public void setIdAlarma(long idalarma) {
		this.idAlarma = idalarma;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTiempoEjecucion() {
		return this.tiempoEjecucion;
	}

	public void setTiempoEjecucion(String tiempoEjecucion) {
		this.tiempoEjecucion = tiempoEjecucion;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

}
