package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoParametro generated by hbm2java
 */
public class CatalogoParametro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4000121645150398401L;
	private long idCatalogoParametro;
	private String parametro;
	private String valor;
	private String descripcion;
	private Set<Mensaje> mensajes = new HashSet<>();
	private Set<Examen> examenes = new HashSet<>();
	private Set<Pregunta> preguntas =new HashSet<>();

	public CatalogoParametro() {
	}

	public CatalogoParametro(long idCatalogoParametro, String parametro, String valor, String descripcion) {
		this.idCatalogoParametro = idCatalogoParametro;
		this.parametro = parametro;
		this.valor = valor;
		this.descripcion = descripcion;
	}

	public CatalogoParametro(long idcatalogoparametro, String parametro, String valor, String descripcion, Set<Mensaje> mensajes,
			Set<Examen> examenes, Set<Pregunta> preguntas) {
		this.idCatalogoParametro = idcatalogoparametro;
		this.parametro = parametro;
		this.valor = valor;
		this.descripcion = descripcion;
		this.mensajes = mensajes;
		this.examenes = examenes;
		this.preguntas = preguntas;
	}

	public long getIdCatalogoParametro() {
		return this.idCatalogoParametro;
	}

	public void setIdCatalogoParametro(long idCatalogoParametro) {
		this.idCatalogoParametro = idCatalogoParametro;
	}

	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Mensaje> getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set<Mensaje> mensajes) {
		this.mensajes = mensajes;
	}

	public Set<Examen> getExamenes() {
		return this.examenes;
	}

	public void setExamenes(Set<Examen> examenes) {
		this.examenes = examenes;
	}

	public Set<Pregunta> getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set<Pregunta> preguntas) {
		this.preguntas = preguntas;
	}

}
