package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1462116425349652647L;
	private long idCiudad;
	private Estado estado;
	private String descripcion;

	public Ciudad() {
	}

	public Ciudad(long idCiudad, Estado estado, String descripcion) {
		this.idCiudad = idCiudad;
		this.estado = estado;
		this.descripcion = descripcion;
	}

	public long getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(long idCiudad) {
		this.idCiudad = idCiudad;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
