package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6434832452641185281L;
	
	private long idCliente;
	private String nombreComercial;
	private String rfc;
	private String direccion;
	private String telefono;
	private String razonSocial;

	public Cliente() {
	}

	public Cliente(long idCliente, String nombreComercial, String rfc, String direccion, String telefono,
			String razonSocial) {
		this.idCliente = idCliente;
		this.nombreComercial = nombreComercial;
		this.rfc = rfc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.razonSocial = razonSocial;
	}

	public long getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(long idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

}
