package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7734795703158570573L;
	private long idEstado;
	private Pais pais;
	private String descripcion;
	private Set<Ciudad> ciudades = new HashSet<Ciudad>();

	public Estado() {
            this.pais = new Pais();
	}

	public Estado(long idEstado, Pais pais, String descripcion) {
		this.idEstado = idEstado;
		this.pais = pais;
		this.descripcion = descripcion;
	}

	public Estado(long idEstado, Pais pais, String descripcion, Set<Ciudad> ciudades) {
		this.idEstado = idEstado;
		this.pais = pais;
		this.descripcion = descripcion;
		this.ciudades = ciudades;
	}

	public long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(long idEstado) {
		this.idEstado = idEstado;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Ciudad> getCiudades() {
		return this.ciudades;
	}

	public void setCiudades(Set<Ciudad> ciudades) {
		this.ciudades = ciudades;
	}

}
