package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 5133228928952125282L;
    private long idExamen;
    private Puesto puesto;
    private CatalogoParametro catalogoParametro;
    private String descripcion;
    private String duracion;
    private List<Pregunta> preguntas = new ArrayList<>();

    private int peguntasAbiertas;
    private int preguntasCerradas;
    private int preguntasMultiples;

    public Examen() {
        this.puesto = new Puesto();
    }

    public Examen(long idExamen, Puesto puesto, CatalogoParametro catalogoParametro, String descripcion,
            String duracion) {
        this.idExamen = idExamen;
        this.puesto = puesto;
        this.catalogoParametro = catalogoParametro;
        this.descripcion = descripcion;
        this.duracion = duracion;
    }

    public Examen(long idExamen, Puesto puesto, CatalogoParametro catalogoParametro, String descripcion,
            String duracion, List<Pregunta> preguntas) {
        this.idExamen = idExamen;
        this.puesto = puesto;
        this.catalogoParametro = catalogoParametro;
        this.descripcion = descripcion;
        this.duracion = duracion;
        this.preguntas = preguntas;
    }

    public long getIdExamen() {
        return this.idExamen;
    }

    public void setIdExamen(long idExamen) {
        this.idExamen = idExamen;
    }

    public Puesto getPuesto() {
        return this.puesto;
    }

    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }

    public CatalogoParametro getCatalogoParametro() {
        return this.catalogoParametro;
    }

    public void setCatalogoParametro(CatalogoParametro catalogoParametro) {
        this.catalogoParametro = catalogoParametro;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getDuracion() {
        return this.duracion;
    }

    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }

    public List<Pregunta> getPreguntas() {
        return preguntas;
    }

    public void setPreguntas(List<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }

    public int getPeguntasAbiertas() {
        return peguntasAbiertas;
    }

    public void setPeguntasAbiertas(int peguntasAbiertas) {
        this.peguntasAbiertas = peguntasAbiertas;
    }

    public int getPreguntasCerradas() {
        return preguntasCerradas;
    }

    public void setPreguntasCerradas(int preguntasCerradas) {
        this.preguntasCerradas = preguntasCerradas;
    }

    public int getPreguntasMultiples() {
        return preguntasMultiples;
    }

    public void setPreguntasMultiples(int preguntasMultiples) {
        this.preguntasMultiples = preguntasMultiples;
    }

}
