package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5109457037135922898L;
	
	private long idmensaje;
	private CatalogoParametro catalogoParametro;
	private String codigo;
	private String descripcion;

	public Mensaje() {
	}

	public Mensaje(long idmensaje, CatalogoParametro catalogoParametro, String codigo, String descripcion) {
		this.idmensaje = idmensaje;
		this.catalogoParametro = catalogoParametro;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public long getIdmensaje() {
		return this.idmensaje;
	}

	public void setIdmensaje(long idmensaje) {
		this.idmensaje = idmensaje;
	}

	public CatalogoParametro getCatalogoParametro() {
		return this.catalogoParametro;
	}

	public void setCatalogoParametro(CatalogoParametro catalogoParametro) {
		this.catalogoParametro = catalogoParametro;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
