package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5677386777177339089L;
	private long idPais;
	private String descripcion;
	private Set<Estado> estados = new HashSet<Estado>();

	public Pais() {
	}

	public Pais(long idPais, String descripcion) {
		this.idPais = idPais;
		this.descripcion = descripcion;
	}

	public Pais(long idPais, String descripcion, Set<Estado> estados) {
		this.idPais = idPais;
		this.descripcion = descripcion;
		this.estados = estados;
	}

	public long getIdPais() {
		return this.idPais;
	}

	public void setIdPais(long idPais) {
		this.idPais = idPais;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

}
