package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7893723884000916252L;

    private long idPregunta;
    private CatalogoParametro catalogoParametro;
    private String descripcion;
    private Set<Respuesta> respuestas = new HashSet<>();
    private Set<Examen> examenes = new HashSet<>();

    public Pregunta() {
    }

    public Pregunta(long idPregunta, CatalogoParametro catalogoParametro, String descripcion) {
        this.idPregunta = idPregunta;
        this.catalogoParametro = catalogoParametro;
        this.descripcion = descripcion;
    }

    public Pregunta(long idPregunta, CatalogoParametro catalogoParametro, String descripcion, Set<Respuesta> respuestas,
            Set<Examen> examenes) {
        this.idPregunta = idPregunta;
        this.catalogoParametro = catalogoParametro;
        this.descripcion = descripcion;
        this.respuestas = respuestas;
        this.examenes = examenes;
    }

    public long getIdPregunta() {
        return this.idPregunta;
    }

    public void setIdPregunta(long idpregunta) {
        this.idPregunta = idpregunta;
    }

    public CatalogoParametro getCatalogoParametro() {
        return this.catalogoParametro;
    }

    public void setCatalogoParametro(CatalogoParametro catalogoParametro) {
        this.catalogoParametro = catalogoParametro;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Respuesta> getRespuestas() {
        return respuestas;
    }

    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }

    public Set<Examen> getExamenes() {
        return this.examenes;
    }

    public void setExamenes(Set<Examen> examenes) {
        this.examenes = examenes;
    }

}
