package com.lam.recursoshumanoscenicco.model;
// Generated 16/09/2018 08:26:45 PM by Hibernate Tools 5.3.1.Final

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3843083888310320825L;
	private long idRespuesta;
	private Pregunta pregunta;
	private String descripcion;
	private String estado;

	public Respuesta() {
	}

	public Respuesta(long idRespuesta, Pregunta pregunta, String descripcion, String estado) {
		this.idRespuesta = idRespuesta;
		this.pregunta = pregunta;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public long getIdRespuesta() {
		return this.idRespuesta;
	}

	public void setIdRespuesta(long idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
